
import java.awt.Container;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * eCWHelp.java
 *
 * Created on Nov 13, 2011, 8:00:27 PM
 */
/**
 *
 * @author Raviraj
 */
public class eCWHelp extends javax.swing.JFrame {

    /** Creates new form eCWHelp */
    public eCWHelp(String title) {
        super(title);
        Container cont = this.getContentPane();
        cont.add(new DBInfo());

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                eCWHelp ecwhelp = new eCWHelp("eClinicalWorks Tech Assistant - developed by Raviraj S");
                ecwhelp.setDefaultCloseOperation(javax.swing.JFrame.EXIT_ON_CLOSE);
                ecwhelp.setSize(830, 550);
                ecwhelp.setLocationRelativeTo(null);
                ecwhelp.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
